config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "groups#index"
  resources :groups, only: [:index,:new, :create] do
    resources :entities, only: [:index, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    can :manage, Group, user_id: user.id
    can :manage, Entity, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :group_entities
  has_and_belongs_to_many :groups

  validates :name, :amount, :user_id, presence: true
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.total_amount(entity)
    sum = 0
    entity.each do |e|
      sum += e.amount
    end
    sum
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_entities
  has_and_belongs_to_many :entities

  validates :name, :icon, presence: true
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :groups, class_name: 'Group', foreign_key: :user_id, dependent: :delete_all
  has_many :entities, class_name: 'Entity', foreign_key: :user_id, dependent: :delete_all

  validates :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @group = Group.find_by(id: params[:group_id])
    @entities = Entity.where(group_id: @group.id)
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.user_id = current_user.id

    if @entity.save
      flash[:success] = 'Transaction created successfully'
      redirect_to group_entities_path, notice: 'Succefully added!'
    else
      flash.now[:error] = 'Entity not saved, try again'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def entity_params
    params.permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @groups = current_user.groups.all.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    if @group.save
      flash[:success] = 'Transaction created successfully'
      redirect_to groups_path, notice: 'Succefully added!'
    else
      flash.now[:error] = 'Group not saved, try again'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/index.html.erb
<div>
  <div class="home-nav">
    <%= link_to  groups_path, class: "btn" do%>
      <i class="fa-solid fa-chevron-left"></i>
    <%end%>
    <h2 class="entity-title"><%= @group.name.capitalize %> Entities</h2>
    <%= link_to  destroy_user_session_path, method: :delete, class: "btn" do%>
      <i class="fa-solid fa-user-slash"></i>
    <%end%>
  </div>
  <div class="braderhumb el-center">
    <span>total transtactions: <%= @entities.sum(:amount) %> </span>
  </div>
  <div class="transactions clm-row">
      <% if @entities.empty? %>
        <p class="empty-clm el-center">There's no transaction yet. <%= link_to "Click here", new_group_entity_path %> to create one.</p>
      <%else%>
        <% @entities.each do |entity| %>
          <div class="card clm-flex-row">
            <div class="entity_descript">
              <div class="details">
                <h3><%= entity.name %></h3>
                <p>$<%= entity.amount %></p>
              </div>
              <span class="card-date"><%= entity.created_at.to_date %></span> 
            </div>
          </div>
        <%end%>
      <%end%>
  </div>
  <%= link_to "Create Entity", new_group_entity_path, class: "btn-link btn-primary el-center active submit" %>
</div>

app/views/entities/new.html.erb
<div class="home-nav">
  <%= link_to  groups_path, class: "btn" do%>
    <i class="fa-solid fa-chevron-left"></i>
  <%end%>
  <h2>New Entity</h2>
  <%= link_to  destroy_user_session_path, method: :delete, class: "btn" do%>
    <i class="fa-solid fa-user-slash"></i>
  <%end%>
</div>
<div class="form-clm">
  <%= form_with model: @group_entity, url: group_entities_path do |f| %>
    <div class="field">
      <%= f.text_field :name, placeholder: 'Transaction name', class: "input_form border" %>
    </div>

    <div class="field">
      <%= f.number_field :amount, placeholder: 'Amount', class: "input_form border" %><br>
    </div>

    <div  class= "input_btn border btn">
      <%= f.submit "Add Transaction", class: "btn-link el-center active submit" %>
    </div>
  <% end %>
</div>

app/views/groups/_home_page.html.erb
<div>
  <div class="home-nav">
    <h2>Transactions</h2>
    <%= link_to  destroy_user_session_path, method: :delete, class: "btn" do%>
      <i class="fa-solid fa-user-slash"></i>
    <%end%>
  </div>
  <div class="transactions clm-row">
      <% if @groups.empty? %>
        <p class="empty-clm">There's no group transaction yet. <%= link_to "Click here", new_group_path %> to create one.</p>
      <%else%>
        <% @groups.each do |group| %>
          <div class="card clm-flex-row">
            <img src=<%=group.icon%> alt="group_icon" class="icon">
            <div class="group_descript">
              <div class="groupe-name clm-flex-row">
                <%= link_to group_entities_path(group.id) do%>
                  <h3><%= group.name %></h3>
                <%end%>
                <p> <%= Entity.where(group_id: group.id).sum(:amount) %>$</p>
              </div>
              <span class="card-date"><%= group.created_at.to_date %></span>
              
            </div>
          </div>
        <%end%>
      <%end%>
  </div>
  <%= link_to "Create Category", new_group_path, class: "btn-link btn-primary el-center active submit" %>
</div>

app/views/groups/_splash.html.erb
<div class="container clm-row">
  <div class="logo-page el-center">
    <h1>MyBudget</h1>
  </div>
  <div class="btn-links clm-row">
    <%= link_to "LOG IN", new_user_session_path, class: "btn-link el-center active" %>
    <%= link_to "SING UP", new_user_registration_path, class: "btn-link el-center" %>.
  </div>
</div>

app/views/groups/index.html.erb
<% if user_signed_in? %>
  <%= render "home_page" %>
<%else%>
  <%= render "splash" %>
<%end%>

app/views/groups/new.html.erb
<div class="home-nav">
  <%= link_to  groups_path, class: "btn" do%>
    <i class="fa-solid fa-chevron-left"></i>
  <%end%>
  <h2>New Transaction</h2>
  <%= link_to  destroy_user_session_path, method: :delete, class: "btn" do%>
    <i class="fa-solid fa-user-slash"></i>
  <%end%>
</div>
<div class="form-clm">
  <%= form_with model: @group do |f| %>
    <div class="field">
      <%= f.text_field :name, placeholder: 'Enter your name', class: "input_form border" %>
    </div>

    <div class="field">
      <%= f.text_field :icon, placeholder: 'Icon link', class: "input_form border" %><br>
    </div>

    <div  class= "input_btn border btn">
      <%= f.submit "Submit", class: "btn-link el-center active submit" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>